### PR TITLE
Fixed the layout based on Svelte project styling

### LINKED ISSUE #39: Fix Raid page layout

### PR DESCRIPTION
**Pull request by juhanakristian**
I based my changes on the styling from the Svelte project. 
Fixes #39

### CODE REVIEW

File: src/routes/raids/ViewRaid.tsx [hunk 1]
```diff
@@ -19,62 +75,66 @@ const ViewRaid = () => {
...
-          </p>
-          <p>
-            <Emoji as="🔥" aria-label="fire" />{' '}
-            {(data?.additions ?? 0) - (data?.deletions ?? 0)} Net Deletions
-          </p>
-        </header>
-        <ol style={{ overflowY: 'auto', height: '90vh' }}>
+      <StatsView>
+        <Header>
+          <div>
```
Comment (tigerabrodi) [inline src/routes/raids/ViewRaid.tsx:102]: Since we have a header, do we really need this `div`?

If we do, it is better to use `section` than `div` due to a11y.

File: src/routes/raids/ViewRaid.tsx [hunk 2]
```diff
@@ -2,12 +2,68 @@ import React, { useEffect, useState } from 'react'
...
+    margin-bottom: 2rem;
+  }
+`
+
+const TotalStats = styled.div`
+  display: flex;
+  flex-direction: row;
+  flex-wrap: wrap;
+
+  > p {
```
Comment (tigerabrodi) [inline src/routes/raids/ViewRaid.tsx:44]: Is there a chance we can create a styled component out of this and not have inlined styles? I know this was initially there, but I would propose creating a styled component and giving it a proper name :+1:.

**Review by tigerabrodi — CHANGES_REQUESTED** [review]

File: src/routes/raids/ViewRaid.tsx [hunk 3]
```diff
@@ -2,12 +2,68 @@ import React, { useEffect, useState } from 'react'
...
+  height: 100vh;
+  display: grid;
+  grid-template-rows: auto 1fr;
+  > * {
+    padding: 1rem;
+  }
+`
+
+const Header = styled.header`
+  z-index: 1;
```
Comment (Aprillion) [inline src/routes/raids/ViewRaid.tsx:23]: hmm, why z-index plz?

Comment (juhanakristian) [reply src/routes/raids/ViewRaid.tsx:23]: Good question :D I'll remove it since it seems unnecessary.

File: src/routes/raids/ViewRaid.tsx (hunk 2 above)
Comment (tigerabrodi) [reply src/routes/raids/ViewRaid.tsx:44]: Has been discussed here: https://github.com/OpenSourceRaidGuild/website/issues/24

Comment (juhanakristian) [reply src/routes/raids/ViewRaid.tsx:43]: My concern with this is that we end up with a lot of components like *Container

File: src/routes/raids/ViewRaid.tsx (hunk 1 above)
Comment (juhanakristian) [reply src/routes/raids/ViewRaid.tsx:101]: The div is just used for layout. I'll change it to section if that's better for a11y.

We will probably need to refactor this layout when we get the site header with navbar though..

Comment (tigerabrodi) [reply src/routes/raids/ViewRaid.tsx]: Let's just refactor it then I guess :+1:

**Review by tigerabrodi — APPROVED** [review]
